import { gsap } from "gsap";
export let classicReverseTL = gsap.timeline();

gsap.set("#weaponSection",{transformOrigin:"center "});

classicReverseTL.to("#ACTIVATE", {duration:0.2, fill:"#D8D8D8"})
                .to("#actView", {duration:0.2, fill:"#D92121", repeat:2})
                .to("#sword", {duration:1, fill:"#CF4037"})
                .to("#homeButton", {duration:0.4, scale:1},"buttonReverse")
                .to("#settingButton", {duration:0.4, scale:1},"buttonReverse")  
                .to("#navigationButton", {duration:0.4, scale:1},"buttonReverse")  
                .to("#musicButton", {duration:0.4, scale:1},"buttonReverse")  
                .to("#cameraButton", {duration:0.4, scale:1},"buttonReverse")  
                .to("#phoneButton", {duration:0.4, scale:1},"buttonReverse")  
                .to("#phoneIcon", {duration:0.4, scale:1, fill:"#000"},"buttonReverse")  
                .to("#homeIcon", {duration:0.4, scale:1, fill:"#000"},"buttonReverse")  
                .to("#homeSection", {duration:0.4, alpha:0},"buttonReverse") 
                .to("#phoneSection", {duration:0.4, alpha:0},"buttonReverse") 
                .to("#mphMeter", {duration:0.5, alpha:0},"gaugeReverse") 
                .to("#rpmMeter", {duration:0.5, alpha:0},"gaugeReverse") 
                .to("#mphAllView", {duration:0.5, alpha:0},"gaugeReverse") 
                .to("#rpmAllView", {duration:0.5, alpha:0},"gaugeReverse") 
                .to("#mphBase", {duration:0.5, alpha:0},"gaugeReverse") 
                .to("#rpmBase", {duration:0.5, alpha:0},"gaugeReverse") 
                .to("#rightFrontDoor", {duration:0.5, alpha:0, y:100},"gaugeReverse")
                .to("#leftFrontDoor", {duration:0.5, alpha:0, y:100},"gaugeReverse")
                .to("#rightFrontCover", {duration:0.5, alpha:0, y:100},"gaugeReverse")
                .to("#leftFrontCover", {duration:0.5, alpha:0, y:100},"gaugeReverse")
                .to("#fuelBar", {duration:0.5, alpha:0, y:640},"gaugeReverse")
                .to("#energonBar", {duration:0.5, alpha:0, y:640},"gaugeReverse")
                .to("#midMouth", {duration:0.5, alpha:0, y:100},"gaugeReverse")
                .to("#FUEL", {duration:0.5, alpha:0, y:100},"gaugeReverse")
                .to("#ENERGON", {duration:0.5, alpha:0, y:100},"gaugeReverse")
                .to("#leftGuardDoorUp", {duration:1, y:-50},"doorReverseOpen")
                .to("#leftGuardDoorDown", {duration:1, y:60},"doorReverseOpen")
                .to("#rightGuardDoorUp", {duration:1, y:-50},"doorReverseOpen")
                .to("#rightGuardDoorDown", {duration:1, y:60},"doorReverseOpen")
                .to("#musicButton", {duration:0.5, alpha:0, scale:0, x:700},"buttonReverseOut3")
                .to("#navigationButton", {duration:0.5, alpha:0, scale:0, x:180},"buttonReverseOut3")
                .to("#homeButton", {duration:0.5, alpha:0, scale:0, x:700},"buttonReverseOut2")
                .to("#phoneButton", {duration:0.5, alpha:0, scale:0, x:180},"buttonReverseOut2")
                .to("#cameraButton", {duration:0.5, alpha:0, scale:0, x:700},"buttonReverseOut")
                .to("#settingButton", {duration:0.5, alpha:0, scale:0, x:180},"buttonReverseOut")
                .to("#leftGuardDoorUp", {duration:1, y:-22},"doorReverseClose")
                 .to("#leftGuardDoorDown", {duration:1, y:32},"doorReverseClose")
                .to("#rightGuardDoorUp", {duration:1, y:-22},"doorReverseClose")
                .to("#rightGuardDoorDown", {duration:1, y:32},"doorReverseClose")
                .to("#weaponSection",{ duration:1, y:380, scale:0, alpha:0 },"ReverseOut")
                .to("#rightHandleDownBase",{ duration:1, y:380, scale:0, alpha:0 },"ReverseOut")
                .to("#leftHandleDownBase",{ duration:1, y:380, scale:0, alpha:0 },"ReverseOut")
                .to("#rightHandleDownView",{ duration:1, y:380, scale:0, alpha:0 },"ReverseOut")
                .to("#leftHandleDownView",{ duration:1, y:380, scale:0, alpha:0 },"ReverseOut")
                .to("#leftHandleUpView",{ duration:1, y:380, scale:0, alpha:0 },"ReverseOut")
                .to("#rightHandleUpView",{ duration:1, y:380, scale:0, alpha:0 },"ReverseOut")
                
         